### ISSUE TITLE
Existing User Requires Email Activation

### ISSUE THREAD

**Issue by ddmcleod** [tripflex/wp-login-flow#34]
I was playing with your plugin on a WP 4.3.1 site. I was logged in as (the only) admin user for this site and everything worked fine until I logged out. When I tried to log back, I was presented with the same login page repeatedly and the url appeared to indicated that my activation was still pending. The only way I could get out of this cycle was to delete the plugin entirely, log back in using my admin credentials and then re-activate the plugin.

This appears to be a serious bug. No matter what settings I select from your admin page, the plugin should always allow the admin user that is activating the plugin to login. No further email activation should be required.

Thanks,

David McLeod

**Comment by ddmcleod** [comment]
I was able to work around this problem by adding a row in the usermeta table with meta_key = 'activation_status' and meta_value="1".

I think you need to automatically do this for the admin user who activates the plugin.

David

**Comment by tripflex** [comment]
Thanks sorry I never responded, I kinda abandoned this plugin after the exact reason I built this plugin, was actually integrated into core of WordPress .. but now i'm fixing it up for v3 release to keep this feature, and make the "Activation" process for registering -- even better than how core currently has it ... which still shows it as "Password Reset" when it's really setting your password .. yada yada ... big things coming soon :)
