### ISSUE TITLE
Reset Password Link not working

### ISSUE THREAD

**Issue by thedigitalcircle** [tripflex/wp-login-flow#44]
Hi
I am using jobify theme including Ultimate Member. When some submit resume using submit resume page, account created but activation of the account email doesn't working.
It is showing "Your password reset link appears to be invalid. Please request a new link below." and it redirect me to WordPress Back End.
http://prntscr.com/r7y9ga

Please help
Shuvashish Saha

**Comment by tripflex** [comment]
So it is sending the correct email, but the link is not working correctly?

**Comment by thedigitalcircle** [comment]
Yes

**Comment by tripflex** [comment]
hmm so I just tested this and i don't seem to have any issues with this, must be the integration between UM and Resume Manager as far as i can tell
